# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/pages', type: :request do
  # This should return the minimal set of attributes required to create a valid Page.
  let(:valid_attributes) do
    attributes_for(:page)
  end

  let(:invalid_attributes) do
    { foo: :bar, fiz: :bang }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      create(:page)
      get pages_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      page = create(:page)
      get page_url(page)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      user = create(:user)
      sign_in user

      get new_page_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      user = create(:user)
      sign_in user

      page = create(:page)
      get edit_page_url(page)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Page' do
        user = create(:user)
        sign_in user

        expect do
          post pages_url, params: { page: valid_attributes }
        end.to change(Page, :count).by(1)
      end

      it 'redirects to the created page' do
        user = create(:user)
        sign_in user

        post pages_url, params: { page: valid_attributes }
        expect(response).to redirect_to(page_url(Page.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Page' do
        user = create(:user)
        sign_in user

        expect do
          post pages_url, params: { page: invalid_attributes }
        end.not_to change(Page, :count)
      end

      it 'renders an unprocessable entity status' do
        user = create(:user)
        sign_in user

        post pages_url, params: { page: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        attributes_for(:page)
      end

      it 'updates the requested page' do
        user = create(:user)
        sign_in user

        page = create(:page)
        patch page_url(page), params: { page: new_attributes }
        page.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the page' do
        user = create(:user)
        sign_in user

        page = create(:page)
        patch page_url(page), params: { page: new_attributes }
        page.reload
        expect(response).to redirect_to(page_url(page))
      end
    end

    context 'with invalid parameters' do
      it "renders a found response (i.e. to display the 'edit' template)" do
        user = create(:user)
        sign_in user

        page = create(:page)
        patch page_url(page), params: { page: invalid_attributes }
        expect(response).to have_http_status(:found)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested page' do
      user = create(:user)
      sign_in user

      page = create(:page)
      expect do
        delete page_url(page)
      end.to change(Page, :count).by(-1)
    end

    it 'redirects to the pages list' do
      user = create(:user)
      sign_in user

      page = create(:page)
      delete page_url(page)
      expect(response).to redirect_to(pages_url)
    end
  end
end
